name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v2

    -
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - 
      name: Build code
      run: ./gradlew build
      
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: wschcom/main-service:latest
