name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-publish:

    runs-on: ubuntu-latest
    
    steps:
    - 
      name: Checkout Code
      uses: actions/checkout@v2

    -
      name: Set Up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - 
      name: Build Code
      run: ./gradlew build
      
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    -
      name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/crebito-dredito:latest
